"""Directed-vector phrase authoring for wiki pages.

Two sources of phrases per page:

  - source='human': pinned in the page's frontmatter `directed:` YAML
                    block. Authoritative; never overwritten by the LLM.
                    synthesis_run_id is NULL.
  - source='llm':   generated by `generate_directed_phrases()` from the
                    page body. Subject to MAX_DIRECTED_VECTORS_PER_DOC
                    cap; subject to dedup against human pins. Carries
                    the synthesis_run_id; older runs' rows are deleted
                    on each regeneration.

`persist_directed_vectors()` is the orchestrator the synthesis path
calls after a wiki page is written. It is best-effort: an LLM failure
logs a warning and skips the LLM contribution but does not roll back
the page write or the human pins.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any

from services.synthesis.providers import (
    DirectedPhrasesProvider,
    get_directed_phrases_provider,
)
from shared.constants import (
    DIRECTED_DEDUPE_COSINE_THRESHOLD,
    MAX_DIRECTED_PHRASE_CHARS,
    MAX_DIRECTED_VECTORS_PER_DOC,
    MAX_HUMAN_DIRECTED_PER_DOC,
)
from shared.db import with_tenant
from shared.embeddings import Embedder
from shared.logging import get_logger

log = get_logger(__name__)


@dataclass(slots=True)
class DirectedPersistResult:
    human_added: int = 0
    human_removed: int = 0
    llm_added: int = 0
    llm_removed: int = 0
    llm_failed: bool = False
    # Drop counts from the cosine-distance dedup pass. Tracked separately
    # so we can see whether DIRECTED_DEDUPE_COSINE_THRESHOLD is too tight
    # (high drop rate -> losing legitimate distinct phrasings) or too
    # loose (zero drops -> storing near-duplicate embeddings). Tuning is
    # eval-driven; these counters are the input.
    llm_dropped_vs_human: int = 0   # LLM phrase too close to a human pin
    llm_dropped_internal: int = 0   # LLM phrase too close to one already kept


# ---------------------------------------------------------------------------
# Frontmatter parsing
# ---------------------------------------------------------------------------


def parse_directed_frontmatter(frontmatter: dict[str, Any] | None) -> list[str]:
    """Extract the `directed:` list from a wiki page's parsed frontmatter.

    Accepts the already-parsed dict that wiki pages carry in their
    `metadata.frontmatter` slot. Returns the list of trigger phrases as
    plain strings; on missing / malformed input, returns [] and logs a
    warning.

    Trust-boundary enforcement (frontmatter is authored input):
      * Empty / whitespace-only entries are dropped.
      * Phrases longer than MAX_DIRECTED_PHRASE_CHARS are dropped (logged
        as oversize). Reject rather than truncate so the operator sees
        the rejected phrase and fixes it upstream.
      * The list is capped at MAX_HUMAN_DIRECTED_PER_DOC entries; overage
        is logged once and dropped silently after that.
    """
    if not isinstance(frontmatter, dict):
        return []
    raw = frontmatter.get("directed")
    if raw is None:
        return []
    if not isinstance(raw, list):
        log.warning(
            "directed.frontmatter_not_list",
            type=type(raw).__name__,
        )
        return []
    out: list[str] = []
    overage_logged = False
    for item in raw:
        if not isinstance(item, str):
            log.warning(
                "directed.frontmatter_non_string_item",
                type=type(item).__name__,
            )
            continue
        stripped = item.strip()
        if not stripped:
            continue
        if len(stripped) > MAX_DIRECTED_PHRASE_CHARS:
            log.warning(
                "directed.frontmatter_phrase_too_long",
                length=len(stripped),
                limit=MAX_DIRECTED_PHRASE_CHARS,
            )
            continue
        if len(out) >= MAX_HUMAN_DIRECTED_PER_DOC:
            if not overage_logged:
                log.warning(
                    "directed.frontmatter_count_capped",
                    cap=MAX_HUMAN_DIRECTED_PER_DOC,
                    seen=len(raw),
                )
                overage_logged = True
            continue
        out.append(stripped)
    return out


# ---------------------------------------------------------------------------
# Hashing + normalization
# ---------------------------------------------------------------------------


def _normalize(phrase: str) -> str:
    """Canonicalize a phrase before hashing: lowercase + collapse whitespace.

    The content_hash uniqueness on directed_vectors keys here, so the
    same engineer pin re-emitted across runs is idempotent. We trim to
    avoid trailing-whitespace duplicates from copy-paste authoring.
    """
    return " ".join(phrase.lower().split())


def _content_hash(phrase: str) -> bytes:
    """SHA-256 of the normalized phrase, truncated to 32 bytes."""
    return hashlib.sha256(_normalize(phrase).encode("utf-8")).digest()


# ---------------------------------------------------------------------------
# LLM phrase generation — provider-routed
# ---------------------------------------------------------------------------
#
# `generate_directed_phrases` was historically an Anthropic-only call with
# its own response-parsing logic. The 2026-05-09 model shootout (eval at
# scripts/eval_directed_phrases.py, judged by Opus 4.7) picked Gemini 3
# Flash as the new default: same latency as Haiku, ~1/4 the cost,
# specificity 8.6 vs 7.8 across 5 fixtures.
#
# Generation now goes through services/synthesis/providers.py:
# `DirectedPhrasesProvider` Protocol with Anthropic + Gemini impls and a
# factory that dispatches on `shared.constants.DIRECTED_PHRASES_MODEL`.
# Tests inject a fake provider; production reads the constant.
# ---------------------------------------------------------------------------


async def generate_directed_phrases(
    *,
    page_title: str,
    page_body: str,
    provider: DirectedPhrasesProvider | None = None,
) -> list[str]:
    """Ask the configured provider for 5-10 trigger phrases describing
    this page's retrieval intent.

    Returns at most MAX_DIRECTED_VECTORS_PER_DOC phrases. Raises on
    provider errors so the caller can decide between log-and-skip
    (default in `persist_directed_vectors`) and harder failure handling.

    `provider` is injectable for tests; default is the configured
    `DIRECTED_PHRASES_MODEL` (Gemini 3 Flash today).
    """
    if provider is None:
        provider = get_directed_phrases_provider()
    return await provider.generate(page_title=page_title, page_body=page_body)


# ---------------------------------------------------------------------------
# Persistence orchestrator
# ---------------------------------------------------------------------------


def _cosine(a: list[float], b: list[float]) -> float:
    """Cosine similarity between two equal-length vectors."""
    if not a or not b:
        return 0.0
    num = sum(x * y for x, y in zip(a, b, strict=True))
    da = sum(x * x for x in a) ** 0.5
    db = sum(y * y for y in b) ** 0.5
    if da == 0.0 or db == 0.0:
        return 0.0
    return num / (da * db)


def _dedupe_against_anchors(
    candidate_vecs: list[list[float]],
    anchor_vecs: list[list[float]],
    *,
    threshold: float,
) -> list[bool]:
    """Return one bool per candidate: True if it should be KEPT (not a near
    duplicate of any anchor under the cosine-distance threshold).

    threshold is a *distance* threshold: cosine_distance < threshold
    means "too similar; drop". Cosine_distance = 1 - cosine_similarity.
    """
    keep: list[bool] = []
    for cv in candidate_vecs:
        is_dup = False
        for av in anchor_vecs:
            sim = _cosine(cv, av)
            dist = 1.0 - sim
            if dist < threshold:
                is_dup = True
                break
        keep.append(not is_dup)
    return keep


def _to_halfvec_literal(vec: list[float]) -> str:
    return "[" + ",".join(f"{x:.7f}" for x in vec) + "]"


async def persist_directed_vectors(
    *,
    customer_id: str,
    doc_id: str,
    page_title: str,
    page_body: str,
    frontmatter: dict[str, Any] | None,
    synthesis_run_id: int | None,
    embedder: Embedder | None = None,
    provider: DirectedPhrasesProvider | None = None,
) -> DirectedPersistResult:
    """End-to-end: parse frontmatter pins, generate LLM phrases, dedupe,
    embed, and reconcile rows in directed_vectors for `(customer_id,
    doc_id)`.

    Reconciliation diff-by-content_hash:
      - source='human' rows whose hash isn't in the new pin set -> DELETE
      - source='human' rows for new hashes -> INSERT (ON CONFLICT DO
        NOTHING — same hash + same doc reuses the row)
      - source='llm' rows from a different synthesis_run_id -> DELETE
        (we always replace LLM contributions on each regen)
      - source='llm' rows for new hashes (with current run_id) -> INSERT

    Best-effort on the LLM half: if generation throws, the human pins
    still reconcile correctly and the LLM contribution is skipped (the
    result.llm_failed flag flips, the page write is unaffected).

    `synthesis_run_id` is the active wiki_synthesis_run row id; required
    when LLM phrases are present (the ck_dv_run_for_llm CHECK enforces
    it). Pass None for human-pin-only paths (e.g. manual-entry pages).
    """
    result = DirectedPersistResult()
    embedder = embedder or Embedder()

    human_phrases = parse_directed_frontmatter(frontmatter)
    human_phrases = list(dict.fromkeys(human_phrases))  # preserve order, dedupe by string

    llm_phrases: list[str] = []
    if synthesis_run_id is not None:
        try:
            llm_phrases = await generate_directed_phrases(
                page_title=page_title,
                page_body=page_body,
                provider=provider,
            )
        except Exception as exc:
            log.warning(
                "directed.llm_generation_failed",
                customer=customer_id,
                doc_id=doc_id,
                error=str(exc),
                error_class=type(exc).__name__,
            )
            result.llm_failed = True
            llm_phrases = []

    # Embed all candidate phrases in one round-trip. Human phrases first
    # so dedupe treats humans as anchors.
    candidate_phrases = human_phrases + llm_phrases
    if not candidate_phrases:
        # Nothing to write; still need to reconcile (e.g. all pins removed).
        # LLM reconcile is gated on llm_failed for the same reason as the
        # main path: a transient LLM error must not wipe last-known-good.
        await _reconcile_human(customer_id, doc_id, set(), {}, result)
        if synthesis_run_id is not None and not result.llm_failed:
            await _reconcile_llm(customer_id, doc_id, [], synthesis_run_id, result)
        return result

    embed_result = await embedder.embed_many(candidate_phrases)
    if embed_result.failed:
        log.warning(
            "directed.embed_failed_partial",
            customer=customer_id,
            doc_id=doc_id,
            failed=len(embed_result.failed),
        )
    embeddings_by_idx = {e.chunk_index: e.embedding for e in embed_result.embedded}

    n_human = len(human_phrases)
    human_vecs: list[list[float]] = []
    human_ok_phrases: list[str] = []
    for i, phrase in enumerate(human_phrases):
        vec = embeddings_by_idx.get(i)
        if vec is None:
            continue
        human_vecs.append(vec)
        human_ok_phrases.append(phrase)

    llm_keep: list[tuple[str, list[float]]] = []
    if llm_phrases:
        llm_vecs_indexed = [
            (n_human + i, p) for i, p in enumerate(llm_phrases)
        ]
        candidate_llm_vecs: list[list[float]] = []
        candidate_llm_phrases: list[str] = []
        for global_idx, phrase in llm_vecs_indexed:
            vec = embeddings_by_idx.get(global_idx)
            if vec is None:
                continue
            candidate_llm_vecs.append(vec)
            candidate_llm_phrases.append(phrase)
        # Dedupe LLM candidates against human pins (humans win) AND against
        # already-kept LLM candidates (no internal duplicates). Drop counts
        # are tracked on `result` so operators can see whether the
        # threshold is over-pruning legitimate distinct phrasings.
        keep_mask = _dedupe_against_anchors(
            candidate_llm_vecs,
            human_vecs,
            threshold=DIRECTED_DEDUPE_COSINE_THRESHOLD,
        )
        result.llm_dropped_vs_human = sum(1 for k in keep_mask if not k)

        kept_vecs: list[list[float]] = []
        for phrase, vec, keep in zip(
            candidate_llm_phrases, candidate_llm_vecs, keep_mask, strict=True
        ):
            if not keep:
                continue
            # Internal LLM dedup: drop if too similar to one we already kept.
            internal_keep = _dedupe_against_anchors(
                [vec], kept_vecs, threshold=DIRECTED_DEDUPE_COSINE_THRESHOLD
            )[0]
            if not internal_keep:
                result.llm_dropped_internal += 1
                continue
            kept_vecs.append(vec)
            llm_keep.append((phrase, vec))
            if len(llm_keep) >= MAX_DIRECTED_VECTORS_PER_DOC:
                break

    # Reconcile human rows against this run's pin set.
    #
    # CRITICAL: build `desired_hashes` from ALL human phrases (regardless
    # of embed success), but `payload` only from successfully-embedded
    # phrases. A transient embedder failure on one human pin must NOT
    # delete that pin's existing row. Pre-fix behavior: pins that failed
    # to embed were missing from human_payload, so desired_hashes excluded
    # them, so to_delete = existing - desired DELETED the still-valid
    # row. The docstring promises pins are authoritative — preserve them
    # across embed flakiness. New rows still need a vector to insert, so
    # _reconcile_human filters to_insert by payload presence.
    desired_human_hashes: set[bytes] = {
        _content_hash(p) for p in human_phrases
    }
    human_payload: dict[bytes, tuple[str, list[float]]] = {}
    for phrase, vec in zip(human_ok_phrases, human_vecs, strict=True):
        h = _content_hash(phrase)
        human_payload.setdefault(h, (phrase, vec))
    await _reconcile_human(
        customer_id, doc_id, desired_human_hashes, human_payload, result
    )

    # Reconcile LLM rows ONLY when LLM generation actually succeeded.
    # On llm_failed=True, llm_keep is [] and calling _reconcile_llm would
    # DELETE the previous run's rows and replace them with nothing —
    # turning a transient LLM hiccup into permanent loss of the doc's
    # LLM-generated trigger phrases. Skipping leaves the last-known-good
    # set in place; the next successful synthesis run reconciles them.
    if synthesis_run_id is not None and not result.llm_failed:
        await _reconcile_llm(
            customer_id, doc_id, llm_keep, synthesis_run_id, result
        )

    return result


async def _reconcile_human(
    customer_id: str,
    doc_id: str,
    desired_hashes: set[bytes],
    payload: dict[bytes, tuple[str, list[float]]],
    result: DirectedPersistResult,
) -> None:
    """Diff existing human rows for the doc against the desired set.

    `desired_hashes`: hashes that must EXIST after this call (= every
        phrase the engineer pinned, regardless of embed success).
    `payload`: subset of `desired_hashes` for which we have a vector
        ready to insert.

    Inserts rows for hashes in `desired_hashes` that aren't yet stored
    AND have a vector in `payload`. Pins whose embed failed pass through
    desired_hashes but NOT payload — the existing row (if any) is
    preserved; nothing is inserted. Uses ON CONFLICT DO NOTHING so
    duplicate inserts are silent (uq_dv_doc_hash enforces idempotency).
    """
    async with with_tenant(customer_id) as conn:
        existing = await conn.fetch(
            """
            SELECT content_hash
            FROM directed_vectors
            WHERE customer_id = $1 AND doc_id = $2 AND source = 'human'
            """,
            customer_id,
            doc_id,
        )
        existing_hashes = {bytes(r["content_hash"]) for r in existing}

        to_delete = existing_hashes - desired_hashes
        # Insert-set is filtered by payload presence: an embed-failed pin
        # passes through desired_hashes (preserving existing row) but
        # cannot be inserted as a new row without a vector.
        to_insert = (desired_hashes - existing_hashes) & set(payload.keys())

        if to_delete:
            await conn.execute(
                """
                DELETE FROM directed_vectors
                WHERE customer_id = $1
                  AND doc_id = $2
                  AND source = 'human'
                  AND content_hash = ANY($3::bytea[])
                """,
                customer_id,
                doc_id,
                list(to_delete),
            )
            result.human_removed = len(to_delete)

        for h in to_insert:
            phrase, vec = payload[h]
            await conn.execute(
                """
                INSERT INTO directed_vectors
                    (customer_id, doc_id, embedding, source_text,
                     source, synthesis_run_id, content_hash)
                VALUES ($1, $2, $3::halfvec, $4, 'human', NULL, $5)
                ON CONFLICT ON CONSTRAINT uq_dv_doc_hash DO NOTHING
                """,
                customer_id,
                doc_id,
                _to_halfvec_literal(vec),
                phrase,
                h,
            )
            result.human_added += 1


async def _reconcile_llm(
    customer_id: str,
    doc_id: str,
    keep: list[tuple[str, list[float]]],
    synthesis_run_id: int,
    result: DirectedPersistResult,
) -> None:
    """Replace LLM rows from older synthesis runs with the new run's set.

    LLM contributions are fully replaced on every regen — the wiki body
    can shift between runs and stale phrases are noise. Older-run rows
    for this doc are deleted in one DELETE; new rows insert with the
    current run id.
    """
    async with with_tenant(customer_id) as conn:
        # Defensive: delete ALL existing llm rows for (cust, doc) before
        # inserting the new run's set. Filtering by `synthesis_run_id <> $3`
        # was technically correct under guaranteed run_id uniqueness, but
        # the same run_id reused for the same doc (e.g. a retry path that
        # doesn't bump run_id, or a future test that reuses ids) would
        # leave the previous call's rows behind alongside the new ones —
        # ON CONFLICT DO NOTHING would silently skip and stale phrases
        # would accumulate. Always-delete is one extra row touch and
        # eliminates the failure mode entirely.
        deleted = await conn.fetch(
            """
            DELETE FROM directed_vectors
            WHERE customer_id = $1
              AND doc_id = $2
              AND source = 'llm'
            RETURNING vector_id
            """,
            customer_id,
            doc_id,
        )
        result.llm_removed = len(deleted)

        for phrase, vec in keep:
            h = _content_hash(phrase)
            await conn.execute(
                """
                INSERT INTO directed_vectors
                    (customer_id, doc_id, embedding, source_text,
                     source, synthesis_run_id, content_hash)
                VALUES ($1, $2, $3::halfvec, $4, 'llm', $5, $6)
                ON CONFLICT ON CONSTRAINT uq_dv_doc_hash DO NOTHING
                """,
                customer_id,
                doc_id,
                _to_halfvec_literal(vec),
                phrase,
                synthesis_run_id,
                h,
            )
            result.llm_added += 1
