#!/usr/bin/env bash
#
# seed_to_customer.sh — paste-friendly synth-to-customer pipeline.
#
# Sources a .env file, materializes a one-off profile YAML, runs
# `synth init` + `synth run --integrate` so plot archetypes (post-regen-
# loop) land in a target customer's R2 bucket + ingestion queue.
#
# Usage:
#   bash scripts/synth/dev/seed_to_customer.sh \
#     --env ~/path/to/.env.local \
#     --customer cust-eval-mahit-demo \
#     [--preset tiny_test] \
#     [--repo github.com/prbe-ai/prbe-knowledge] \
#     [--repo-local ~/Desktop/prbe/prbe-knowledge] \
#     [--seed 7] \
#     [--time-window 30d] \
#     [--mock-llm | --record-llm] \
#     [--no-regen]
#
# Required env vars in the sourced .env (or already exported):
#   DATABASE_URL, DATABASE_URL_SYNC,
#   R2_ENDPOINT_URL, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_REGION,
#   ANTHROPIC_API_KEY  (skip with --mock-llm)
#   OPENAI_API_KEY     (skip with --mock-llm)
#
# Fails loudly on missing env vars and on bad customer_id prefixes.

set -euo pipefail

# --- defaults ----------------------------------------------------------------
ENV_FILE=""
CUSTOMER_ID=""
PRESET="tiny_test"
REPO_URL="github.com/prbe-ai/prbe-knowledge"
REPO_LOCAL=""
SEED="7"
TIME_WINDOW="30d"
MOCK_LLM=""
RECORD_LLM=""
NO_REGEN=""

# --- arg parsing -------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)         ENV_FILE="$2"; shift 2 ;;
    --customer)    CUSTOMER_ID="$2"; shift 2 ;;
    --preset)      PRESET="$2"; shift 2 ;;
    --repo)        REPO_URL="$2"; shift 2 ;;
    --repo-local)  REPO_LOCAL="$2"; shift 2 ;;
    --seed)        SEED="$2"; shift 2 ;;
    --time-window) TIME_WINDOW="$2"; shift 2 ;;
    --mock-llm)    MOCK_LLM="--mock-llm"; shift 1 ;;
    --record-llm)  RECORD_LLM="--record-llm"; shift 1 ;;
    --no-regen)    NO_REGEN="--no-regen"; shift 1 ;;
    -h|--help)
      sed -n '2,40p' "$0"; exit 0 ;;
    *)
      echo "error: unknown arg: $1" >&2; exit 2 ;;
  esac
done

# --- validation --------------------------------------------------------------
if [[ -z "$ENV_FILE" ]]; then
  echo "error: --env <path> is required" >&2
  exit 2
fi
if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: env file not found: $ENV_FILE" >&2
  exit 2
fi
if [[ -z "$CUSTOMER_ID" ]]; then
  echo "error: --customer <id> is required" >&2
  exit 2
fi
case "$CUSTOMER_ID" in
  cust-eval-*|cust-synth-*) ;;
  *)
    echo "error: customer_id must start with 'cust-eval-' or 'cust-synth-' (got: $CUSTOMER_ID)" >&2
    echo "       The synth CLI refuses to operate on production-shaped tenants." >&2
    exit 2
    ;;
esac
if [[ -n "$MOCK_LLM" && -n "$RECORD_LLM" ]]; then
  echo "error: --mock-llm and --record-llm are mutually exclusive" >&2
  exit 2
fi

# --- source .env (any var defined in the file becomes exported) -------------
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

# --- env-var sanity check ---------------------------------------------------
need_keys=("DATABASE_URL" "DATABASE_URL_SYNC" "R2_ENDPOINT_URL" "R2_ACCESS_KEY_ID" "R2_SECRET_ACCESS_KEY" "R2_REGION")
if [[ -z "$MOCK_LLM" ]]; then
  need_keys+=("ANTHROPIC_API_KEY" "OPENAI_API_KEY")
fi
missing=()
for k in "${need_keys[@]}"; do
  if [[ -z "${!k:-}" ]]; then
    missing+=("$k")
  fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "error: missing required env vars (sourced from $ENV_FILE): ${missing[*]}" >&2
  exit 3
fi

# --- repo-extraction sanity (init reads the repo to build WorldModel) -------
if [[ -z "$REPO_LOCAL" ]]; then
  echo "warn: --repo-local not set; init will clone $REPO_URL via GITHUB_TOKEN if needed." >&2
fi

# --- compose stack health (best-effort) -------------------------------------
if command -v docker >/dev/null 2>&1; then
  if ! docker compose ps 2>/dev/null | grep -q "Up"; then
    echo "warn: docker compose stack does not appear to be up. Run 'docker compose up -d' first." >&2
  fi
fi

# --- materialize a temp profile --------------------------------------------
PROFILE_DIR="$(mktemp -d -t synth-profile.XXXXXX)"
PROFILE_PATH="$PROFILE_DIR/profile.yaml"

{
  echo "# Generated by scripts/synth/dev/seed_to_customer.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "customer_id: $CUSTOMER_ID"
  echo "preset: $PRESET"
  echo "seed: $SEED"
  echo ""
  echo "repos:"
  if [[ -n "$REPO_LOCAL" ]]; then
    echo "  - url: $REPO_URL"
    echo "    local_path: $REPO_LOCAL"
  else
    echo "  - $REPO_URL"
  fi
  echo ""
  echo "world_model:"
  echo "  min_commits_per_persona: 2"
  echo "  topic_pool_lookback_days: 30"
  echo ""
  echo "time_window:"
  echo "  days: ${TIME_WINDOW%d}"
  echo ""
  echo "regen:"
  echo "  max_rounds: 3"
} >"$PROFILE_PATH"

echo ">> profile written: $PROFILE_PATH"
echo ">> customer:        $CUSTOMER_ID"
echo ">> preset:          $PRESET"
echo ">> regen flag:      ${NO_REGEN:-(enabled)}"
echo ">> llm mode:        ${MOCK_LLM:-${RECORD_LLM:-real}}"
echo ""

# --- run the pipeline -------------------------------------------------------
echo ">> [1/2] synth init"
uv run python -m scripts.synth.cli init --profile "$PROFILE_PATH"

echo ""
echo ">> [2/2] synth run --integrate"
# shellcheck disable=SC2086
uv run python -m scripts.synth.cli run \
  --profile "$PROFILE_PATH" \
  --integrate \
  --time-window "$TIME_WINDOW" \
  $MOCK_LLM $RECORD_LLM $NO_REGEN

echo ""
echo ">> done. Synthetic docs are in R2 + ingestion_queue for $CUSTOMER_ID."
echo ">> Next steps:"
echo "   - Tail the worker:    docker compose logs -f worker"
echo "   - Verify retrieval:   curl your retrieval API with this customer_id"
echo "   - Tear down later:    uv run python -m scripts.synth.cli clean --customer $CUSTOMER_ID"
