"""INCIDENT plot archetype — async scenario builder.

Emits 5 docs per scenario:
  1. Sentry alert      — TEMPLATED (no LLM Writer call)
  2. Slack thread      — LLM Writer
  3. Linear issue      — LLM Writer
  4. Notion postmortem — LLM Writer
  5. GitHub fix PR     — LLM Writer

The planner emits 2 eval questions:
  - easy:               "What caused the {svc} outage on {date}?"
  - medium-cross-source: "Who reported the {svc} outage and who fixed it?"

All emitted SynthDocs carry the full cast in `personas` (the planner's
reporter/fixer role distinction is captured in the planner prompt context
but not in the SynthDoc.personas field, which lists all participants).
"""

from __future__ import annotations

import textwrap
from collections.abc import AsyncIterator
from datetime import datetime

from scripts.synth.archetypes.base import (
    Archetype,
    Cadence,
    Category,
    ScenarioSpec,
    Source,
    ValidatorLevel,
)
from scripts.synth.archetypes.plot_base import with_abs_prompt_path
from scripts.synth.company_context import CompanyContext
from scripts.synth.llm.planner import LLMPlanner
from scripts.synth.llm.writer import LLMWriter
from scripts.synth.output.base import SynthDoc
from scripts.synth.ownership import OwnershipIndex
from scripts.synth.scenarios import TimeWindow
from scripts.synth.world_model import WorldModel

INCIDENT = Archetype(
    name="INCIDENT",
    category=Category.PLOT,
    cadence=Cadence.AD_HOC,
    sources_used=(Source.SENTRY, Source.SLACK, Source.LINEAR, Source.NOTION, Source.GITHUB),
    cast_size=(2, 4),
    needs_planner_call=True,
    validator_level=ValidatorLevel.STRICT,
    eval_question_count=2,
    spec_template_path="planner_incident.txt",
)

_SENTRY_TEMPLATE = textwrap.dedent("""\
    SentryAlert: {title}

    service: {service}
    level: error
    culprit: {culprit}
    environment: production
    occurred_at: {ts}

    Stacktrace (abbreviated):
      File "src/{service}/handler.py", line 42, in handle_request
        raise ServiceError("unexpected state")
      File "src/{service}/middleware.py", line 18, in __call__
        return self.app(scope, receive, send)

    This alert was auto-generated by the synthetic corpus builder.
""")


async def build_incident_scenarios(
    world: WorldModel,
    ownership: OwnershipIndex,
    company_ctx: CompanyContext,
    time_window: TimeWindow,
    seed: int,
    *,
    planner: LLMPlanner,
    writer: LLMWriter,
    count: int,
) -> AsyncIterator[tuple[ScenarioSpec, list[SynthDoc]]]:
    """Yield (spec, materialized_docs) for each INCIDENT scenario.

    The ScenarioRunner (Phase E, Task 19) consumes this async iterator and
    threads docs through Validator Pass 2 + IngestionWriter.

    Instance timestamps are picked deterministically from world.time_anchors
    ranked by activity_score descending, cycling with (seed + i) modulo spread.
    """
    anchors = sorted(world.time_anchors, key=lambda a: a.activity_score, reverse=True)
    n_anchors = max(len(anchors), 1)

    # Resolve the relative prompt template path to an absolute path so
    # assemble_planner_prompt can read the file regardless of cwd.
    incident_archetype = with_abs_prompt_path(INCIDENT)

    for i in range(count):
        # Pick instance_ts deterministically: use anchor.end as the reference ts
        anchor_idx = (seed + i) % n_anchors
        instance_ts: datetime = (
            anchors[anchor_idx].end if anchors else time_window.end
        )

        # --- Planner call (1 LLM call) ---
        spec = await planner.plan(
            archetype=incident_archetype,
            world=world,
            ownership=ownership,
            company_ctx=company_ctx,
            instance_ts=instance_ts,
            rng_seed=seed + i,
        )

        # --- Templated Sentry doc (no LLM call) ---
        affected_svc = spec.affected_services[0] if spec.affected_services else "unknown-svc"
        sentry_text = _SENTRY_TEMPLATE.format(
            title=spec.title,
            service=affected_svc,
            culprit=f"{affected_svc}.handler",
            ts=instance_ts.isoformat(),
        )
        sentry_doc = SynthDoc(
            id=f"{spec.id}-sentry-0",
            source=Source.SENTRY,
            source_event_id=f"{spec.id}-sentry-0",
            text=sentry_text,
            occurred_at=instance_ts,
            channel=None,
            page_id=None,
            thread_parent_id=None,
            scenario_id=spec.id,
            archetype=INCIDENT.name,
            # spec.cast is tuple[str, ...] of canonical_ids; include all for the sentry alert
            personas=tuple(spec.cast),
            services_mentioned=(affected_svc,),
            priority=10,
        )

        # --- LLM Writer calls for the 4 remaining sources ---
        prior_docs: tuple[SynthDoc, ...] = (sentry_doc,)
        non_sentry_sources = [Source.SLACK, Source.LINEAR, Source.NOTION, Source.GITHUB]
        llm_docs: list[SynthDoc] = []

        for emission_idx, source in enumerate(non_sentry_sources):
            text = await writer.write(
                spec=spec,
                source=source,
                emission_index=emission_idx,
                prior_emitted_docs=prior_docs,
                world=world,
                company_ctx=company_ctx,
            )
            doc = SynthDoc(
                id=f"{spec.id}-{source.value}-{emission_idx}",
                source=source,
                source_event_id=f"{spec.id}-{source.value}-{emission_idx}",
                text=text,
                occurred_at=instance_ts,
                channel="#incidents" if source == Source.SLACK else None,
                page_id=f"{spec.id}-notion-0" if source == Source.NOTION else None,
                thread_parent_id=None,
                scenario_id=spec.id,
                archetype=INCIDENT.name,
                personas=tuple(spec.cast),
                services_mentioned=tuple(spec.affected_services),
                priority=20 + emission_idx,
            )
            llm_docs.append(doc)
            prior_docs = (*prior_docs, doc)

        all_docs = [sentry_doc, *llm_docs]
        yield spec, all_docs


