# Generated by scripts/sync_credential_scrubber.py; edit the agent source.
"""Artifact boundary: block readable credentials and warn on incomplete inspection.

Artifacts are never redacted in place: changing model/config bytes corrupts them.
Recognized credentials are refused, including inside supported encodings and
containers. Opaque content uploads with a warning by default; that policy never
permits recognized credentials. Resource limits still refuse the operation.
"""

from __future__ import annotations

import base64
import functools
import gzip
import hashlib
import inspect
import io
import os
import re
import stat
import tarfile
import tempfile
import warnings
import zipfile
import zlib
from contextlib import contextmanager
from contextvars import ContextVar
from dataclasses import dataclass
from pathlib import Path

from ._credential_redaction import default_scrub
from ._credential_secrets import scan


class CredentialBlocked(Exception):
    """A safe, value-free refusal, deliberately outside fail-open exception sets."""


class ArtifactInspectionWarning(RuntimeWarning):
    """Uploading bytes whose full contents could not be checked for credentials."""


@dataclass(frozen=True)
class InspectionResult:
    warnings: tuple[str, ...] = ()

    @property
    def fully_inspected(self) -> bool:
        return not self.warnings

    @property
    def warning_message(self) -> str | None:
        if not self.warnings:
            return None
        return (
            "WARNING: Artifact upload allowed without full credential inspection. "
            + "; ".join(self.warnings)
            + ". Probe cannot confirm this file is free of secrets. "
            "Check its hidden contents before sharing."
        )


def warn_if_incomplete(result: InspectionResult) -> None:
    if result.warning_message:
        warnings.warn(result.warning_message, ArtifactInspectionWarning, stacklevel=3)


@dataclass(frozen=True)
class ScanPolicy:
    max_bytes: int = 64 * 1024 * 1024
    max_expanded_bytes: int = 128 * 1024 * 1024
    max_members: int = 1024
    max_depth: int = 4
    allow_opaque: bool = True


def policy() -> ScanPolicy:
    # An optional stricter local policy never waives a readable credential finding.
    return ScanPolicy(allow_opaque=os.environ.get("PROBE_ARTIFACT_OPAQUE_POLICY") != "block")


def _refuse(reason: str) -> None:
    # Never interpolate a filename, content, archive member, or exception value.
    raise CredentialBlocked("Artifact upload refused: " + reason) from None


def _has_findings(text: str) -> bool:
    try:
        return bool(scan(text)) or default_scrub(text) != text
    except Exception:
        _refuse("credential inspection failed")


_BASE64 = re.compile(r"(?<![A-Za-z0-9+/])[A-Za-z0-9+/]{24,}={0,2}(?![A-Za-z0-9+/])")


def inspect_bytes(raw: bytes, *, scan_policy: ScanPolicy | None = None) -> InspectionResult:
    limits = scan_policy or policy()
    budget = [limits.max_expanded_bytes]
    members = [0]
    incomplete_reasons: list[str] = []

    def incomplete(reason: str) -> None:
        if not limits.allow_opaque:
            _refuse(reason)
        if reason not in incomplete_reasons:
            incomplete_reasons.append(reason)

    def read_expanded(stream) -> tuple[bytes, bool]:
        """Retain output before a later member/trailer failure, under one cap."""
        cap = min(limits.max_bytes, budget[0])
        expanded = bytearray()
        try:
            while True:
                # read1 returns decoded data before looking for the next gzip
                # member. A single read(all) can discard that data on failure.
                chunk = stream.read1(min(64 * 1024, cap - len(expanded) + 1))
                if not chunk:
                    return bytes(expanded), False
                expanded.extend(chunk)
                if len(expanded) > cap:
                    _refuse("expanded content exceeds inspection limit")
        except (OSError, EOFError, ValueError, RuntimeError, zlib.error):
            return bytes(expanded), True

    def bound_zip_reader(stream, *, recover: bool = False) -> None:
        # The ZIP's declared uncompressed size is untrusted. ZipExtFile clips
        # output to _left, so a forged short size plus a matching prefix CRC
        # would otherwise hide a readable decompressed suffix without error.
        if not isinstance(stream, zipfile.ZipExtFile) or not (
            hasattr(stream, "_expected_crc") and hasattr(stream, "_left")
        ):
            _refuse("archive recovery is unavailable")
        stream._left = min(limits.max_bytes, budget[0]) + 1
        if recover:
            stream._expected_crc = None

    def inspect_blob(data: bytes, depth: int, *, candidate: bool = False) -> None:
        if depth > limits.max_depth:
            _refuse("nested encoding exceeds inspection limit")
        budget[0] -= len(data)
        if budget[0] < 0:
            _refuse("expanded content exceeds inspection limit")
        # ASCII credentials must be found even in a binary wrapper.
        text = None
        encodings = ["utf-8-sig"]
        if data.startswith((b"\xff\xfe\x00\x00", b"\x00\x00\xfe\xff")):
            encodings.insert(0, "utf-32")
        elif data.startswith((b"\xff\xfe", b"\xfe\xff")):
            encodings.insert(0, "utf-16")
        elif data and data.count(b"\x00") >= len(data) / 4:
            encodings += ["utf-16-le", "utf-16-be", "utf-32-le", "utf-32-be"]
        texts = []
        for encoding in encodings:
            try:
                decoded = data.decode(encoding)
            except (UnicodeError, ValueError):
                continue
            texts.append(decoded)
            if text is None:
                text = decoded
        # Legacy Western text is supported only when the whole decoded file
        # is printable prose. Never reinterpret a malformed UTF BOM as cp1252.
        if text is None and not data.startswith((b"\xff\xfe", b"\xfe\xff", b"\x00\x00\xfe\xff")):
            try:
                legacy = data.decode("cp1252")
            except UnicodeError:
                pass
            else:
                if (
                    all(c.isprintable() or c in "\t\r\n" for c in legacy)
                    and sum(ord(c) < 128 for c in legacy) >= len(legacy) / 2
                ):
                    text = legacy
                    texts.append(legacy)
        readable_text = any(
            all(c.isprintable() or c in "\t\r\n" for c in decoded) for decoded in texts
        )
        # Always retain an ASCII-preserving view, even when an unrelated UTF-16
        # decode succeeds on an arbitrary binary prefix.
        texts.append(data.decode("utf-8", errors="replace"))
        for decoded in texts:
            if _has_findings(decoded):
                _refuse("credential detected; remove it before uploading")

        if data.startswith(b"\x1f\x8b"):
            try:
                with gzip.GzipFile(fileobj=io.BytesIO(data)) as archive:
                    expanded, damaged = read_expanded(archive)
            except (OSError, EOFError, zlib.error):
                incomplete("compressed content could not be inspected")
                return
            inspect_blob(expanded, depth + 1)
            if damaged:
                incomplete("compressed content could not be inspected")
            return
        if data.startswith((b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08")):
            try:
                with zipfile.ZipFile(io.BytesIO(data)) as archive:
                    for member in archive.infolist():
                        members[0] += 1
                        if members[0] > limits.max_members:
                            _refuse("archive member count exceeds inspection limit")
                        if _has_findings(member.filename) or _has_findings(
                            member.comment.decode("utf-8", errors="replace")
                        ):
                            _refuse("credential detected in archive metadata")
                        if member.flag_bits & 1:
                            incomplete("encrypted archive contents could not be inspected")
                            continue
                        if member.is_dir():
                            continue
                        if member.file_size > limits.max_bytes or member.file_size > budget[0]:
                            _refuse("expanded content exceeds inspection limit")
                        expanded = b""
                        try:
                            with archive.open(member) as stream:
                                bound_zip_reader(stream)
                                expanded, damaged = read_expanded(stream)
                                if damaged:
                                    raise zipfile.BadZipFile("member inspection incomplete")
                        except (
                            OSError,
                            ValueError,
                            RuntimeError,
                            zipfile.BadZipFile,
                            NotImplementedError,
                            zlib.error,
                        ):
                            # ZipExtFile validates CRC before returning its final
                            # plaintext chunk. An invalid CRC must not erase that
                            # readable content from inspection. Reopen solely for
                            # recovery, keeping standard ZIP decompression and the
                            # bounded reader, but without the integrity verdict.
                            # These stdlib-private fields are checked explicitly:
                            # incompatible implementations fail closed rather than
                            # silently claiming recovery succeeded.
                            try:
                                with archive.open(member) as stream:
                                    bound_zip_reader(stream, recover=True)
                                    recovered, _ = read_expanded(stream)
                            except (
                                OSError,
                                EOFError,
                                ValueError,
                                RuntimeError,
                                zipfile.BadZipFile,
                                NotImplementedError,
                                zlib.error,
                            ):
                                recovered = b""
                            if recovered or expanded:
                                inspect_blob(recovered or expanded, depth + 1)
                            incomplete("archive member could not be inspected")
                            continue
                        inspect_blob(expanded, depth + 1)
            except (OSError, ValueError, RuntimeError, zipfile.BadZipFile, NotImplementedError):
                incomplete("archive could not be inspected")
            return

        if len(data) >= 512 and data[257:262] == b"ustar":
            try:
                with tarfile.open(fileobj=io.BytesIO(data), mode="r:") as archive:
                    for member in archive:
                        members[0] += 1
                        if members[0] > limits.max_members:
                            _refuse("archive member count exceeds inspection limit")
                        if _has_findings(member.name) or _has_findings(member.linkname):
                            _refuse("credential detected in archive metadata")
                        if not member.isfile():
                            continue
                        if member.size > limits.max_bytes or member.size > budget[0]:
                            _refuse("expanded content exceeds inspection limit")
                        try:
                            stream = archive.extractfile(member)
                        except (OSError, tarfile.TarError, ValueError):
                            incomplete("archive member could not be inspected")
                            continue
                        if stream is None:
                            incomplete("archive member could not be inspected")
                            continue
                        try:
                            with stream:
                                expanded = stream.read(min(limits.max_bytes, budget[0]) + 1)
                        except (OSError, tarfile.TarError, ValueError):
                            incomplete("archive member could not be inspected")
                            continue
                        inspect_blob(expanded, depth + 1)
            except (OSError, tarfile.TarError, ValueError):
                incomplete("archive could not be inspected")
            return

        if text is not None:
            for match in _BASE64.finditer(text):
                value = match.group()
                # Candidates embedded in prose are only further inspected if
                # decoding produces text; random IDs are not opaque artifacts.
                try:
                    decoded = base64.b64decode(value + "=" * (-len(value) % 4), validate=True)
                except ValueError:
                    continue
                if decoded == data:
                    continue
                if decoded.startswith(
                    (b"\x1f\x8b", b"PK\x03\x04", b"\xff\xfe", b"\xfe\xff")
                ) or all(c in (9, 10, 13) or 32 <= c < 127 for c in decoded):
                    inspect_blob(decoded, depth + 1, candidate=True)
        if not candidate and not readable_text:
            incomplete("opaque binary content could not be fully inspected")

    if len(raw) > limits.max_bytes:
        _refuse("file exceeds inspection size limit")
    try:
        inspect_blob(raw, 0)
    except CredentialBlocked:
        raise
    except Exception:
        _refuse("content inspection failed")
    return InspectionResult(warnings=tuple(incomplete_reasons))


def _read_checked(stream, *, scan_policy: ScanPolicy | None = None) -> bytes:
    limits = scan_policy or policy()
    raw = stream.read(limits.max_bytes + 1)
    if not isinstance(raw, bytes):
        _refuse("upload source is not a binary stream")
    warn_if_incomplete(inspect_bytes(raw, scan_policy=limits))
    return raw


def read_upload(path, *, scan_policy: ScanPolicy | None = None) -> bytes:
    if _has_findings(os.fspath(path)):
        _refuse("credential detected in source path")
    try:
        fd = os.open(path, os.O_RDONLY | getattr(os, "O_NONBLOCK", 0))
        with os.fdopen(fd, "rb") as stream:
            info = os.fstat(stream.fileno())
            if not stat.S_ISREG(info.st_mode):
                _refuse("upload source must be a regular file")
            if info.st_size > (scan_policy or policy()).max_bytes:
                _refuse("file exceeds inspection size limit")
            return _read_checked(stream, scan_policy=scan_policy)
    except OSError:
        _refuse("upload source could not be inspected")


def check_upload(path, *, force: bool = False, is_reference: bool = False) -> None:
    if path is not None and not is_reference:
        # force is intentionally unable to waive a credential finding.
        read_upload(path)


def safe_snapshot_file(source, destination) -> None:
    raw = read_upload(source)
    # No destination exists until ALL bytes have passed inspection.
    fd = os.open(destination, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as stream:
        stream.write(raw)
        stream.flush()
        os.fsync(stream.fileno())


_SOURCE_PATHS = ContextVar("probe_checked_upload_sources", default=None)


def original_upload_path(path):
    return (_SOURCE_PATHS.get() or {}).get(os.fspath(path), os.fspath(path))


@contextmanager
def checked_upload(path, *, digest=None, size=None):
    raw = read_upload(path)
    if (digest is not None and hashlib.sha256(raw).hexdigest() != digest) or (
        size is not None and len(raw) != size
    ):
        _refuse("source changed since its fingerprint was taken")
    fd, frozen = tempfile.mkstemp(prefix="probe-checked-", suffix=Path(path).suffix)
    token = _SOURCE_PATHS.set({**(_SOURCE_PATHS.get() or {}), frozen: original_upload_path(path)})
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(raw)
        del raw
        yield frozen
    finally:
        _SOURCE_PATHS.reset(token)
        Path(frozen).unlink(missing_ok=True)


@contextmanager
def checked_stream(stream, *, size=None):
    # Inspect precisely the bytes promised for this stream. A verified capture
    # deliberately excludes bytes appended after its manifest was taken.
    if size is None:
        raw = _read_checked(stream)
    else:
        if size < 0 or size > policy().max_bytes:
            _refuse("file exceeds inspection size limit")
        raw = stream.read(size)
        if len(raw) != size:
            _refuse("source size changed before upload")
        warn_if_incomplete(inspect_bytes(raw))
    with io.BytesIO(raw) as frozen:
        yield frozen


def freeze_upload(fn):
    """Protect a path-taking upload core with an inspected immutable snapshot."""
    signature = inspect.signature(fn)

    @functools.wraps(fn)
    def wrapped(*args, **kwargs):
        bound = signature.bind(*args, **kwargs)
        path = bound.arguments["path"]
        digest = bound.arguments.get("digest", bound.arguments.get("content_hash"))
        size = bound.arguments.get("size", bound.arguments.get("size_bytes"))
        with checked_upload(path, digest=digest, size=size) as frozen:
            bound.arguments["path"] = frozen
            return fn(*bound.args, **bound.kwargs)

    return wrapped


def freeze_stream(fn):
    signature = inspect.signature(fn)

    @functools.wraps(fn)
    def wrapped(*args, **kwargs):
        bound = signature.bind(*args, **kwargs)
        original = bound.arguments["fh"]
        original.seek(0)
        with checked_stream(original, size=bound.arguments["size"]) as frozen:
            if len(frozen.getbuffer()) != bound.arguments["size"]:
                _refuse("source size changed before upload")
            bound.arguments["fh"] = frozen
            return fn(*bound.args, **bound.kwargs)

    return wrapped
