# Generated by scripts/sync_credential_scrubber.py; edit the agent source.
"""Mandatory scrubbing for captured SDK data and outbound JSON payloads.

Field names provide context for opaque credentials; the shared tap scanner
recognizes credentials in free text. Neither auth headers nor SDK Settings
pass through this module. Failures propagate so callers cannot send raw data.
"""

from __future__ import annotations

import json
import re
from typing import Any
from urllib.parse import parse_qsl, unquote, urlencode, urlsplit, urlunsplit

_CREDENTIAL_URI = re.compile(r"(?<![A-Za-z0-9+.-])(?P<scheme>[A-Za-z][A-Za-z0-9+.-]*://)[^/@\s]+@")
_SENSITIVE_KEYS = {
    "api_key",
    "apikey",
    "aws_access_key_id",
    "authorization",
    "auth_token",
    "access_token",
    "bearer_token",
    "cookie",
    "credential",
    "credentials",
    "id_token",
    "password",
    "passwd",
    "pwd",
    "set_cookie",
    "private_key",
    "refresh_token",
    "secret",
    "token",
    "wandb_key",
}
#: Tokenizer vocabulary entries, not credentials -- "_token" suffixes that
#: must SURVIVE scrubbing (an eos_token in a training config is data).
_MODEL_TOKEN_KEYS = {
    "bos_token",
    "cls_token",
    "eos_token",
    "mask_token",
    "pad_token",
    "sep_token",
    "stop_token",
    "unk_token",
}


def is_sensitive_key(key: str) -> bool:
    # Generated dictionary-key placeholders are labels, not credential fields.
    # Re-scrubbing them must not erase their already-scrubbed sibling values.
    if re.fullmatch(r"<redacted(?::[a-z0-9-]+)?>(?::[0-9]+)?", key):
        return False
    separated = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", key)
    separated = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", separated)
    normalized = re.sub(r"[^a-z0-9]+", "_", separated.lower()).strip("_")
    parts = set(normalized.split("_"))
    token_secret = normalized.endswith("_token") and normalized not in _MODEL_TOKEN_KEYS
    signed_secret = normalized.endswith(("_signature", "_sig"))
    # `<vendor>_api_key` is a credential in every case we have met, and the
    # value alone cannot tell you: a wandb key is 40 lowercase hex characters,
    # the same shape as content hashes that must be preserved. The KEY NAME is the only signal, so it has to be enough.
    # Deliberately `_api_key` and not `_key`: `sort_key`, `primary_key` and
    # `group_key` are ordinary config fields and eating them would make the
    # scrubber something people turn off.
    vendor_api_key = normalized.endswith("_api_key")
    return (
        normalized in _SENSITIVE_KEYS
        or token_secret
        or signed_secret
        or vendor_api_key
        or bool(parts & {"password", "secret", "credential", "credentials"})
    )


#: URL-shaped spans INSIDE a larger string. The query scrubber used to require
#: the whole value to parse as a URL, which meant it never fired on the shape it
#: actually meets in the wild -- `TransportError("GET https://h/x?token=S: boom")`
#: has no scheme at position 0, so urlsplit returned early and the token
#: survived. Substring matching is what makes it real.
_EMBEDDED_URL = re.compile(r"(?<![A-Za-z0-9+.-])[A-Za-z][A-Za-z0-9+.-]*://[^\s'\"<>]+")


def _scrub_url(url: str) -> str:
    try:
        parsed = urlsplit(url)
    except ValueError:
        return _CREDENTIAL_URI.sub(r"\g<scheme><redacted>@", url)
    if not parsed.scheme or not parsed.netloc:
        return url
    # Parse before introducing '<redacted>': angle brackets terminate the URL
    # matcher, and replacing userinfo first used to hide its entire query.
    netloc = parsed.netloc
    if "@" in netloc:
        netloc = "<redacted>@" + netloc.rsplit("@", 1)[1]
    def parameters(value: str) -> str:
        value = value.replace("%3Credacted%3E", "<redacted>")
        pairs = parse_qsl(value, keep_blank_values=True)
        if not any(is_sensitive_key(k) and v not in ("", "<redacted>") for k, v in pairs):
            return value
        return urlencode([(k, "<redacted>" if is_sensitive_key(k) else v) for k, v in pairs]).replace("%3Credacted%3E", "<redacted>")
    query, fragment = parameters(parsed.query), parameters(parsed.fragment)
    if netloc == parsed.netloc and query == parsed.query and fragment == parsed.fragment:
        return url  # No credential changed; retain scheme case and URL spelling.
    return urlunsplit((parsed.scheme, netloc, parsed.path, query, fragment))


def scrub_string(value: str, *, _depth: int = 0) -> str:
    """Scrub secrets in prose without removing ordinary paths or identifiers."""
    from ._credential_secrets import redact

    # Inspect the original credential before ordinary scrubbing can remove
    # its prefix and leave a NUL-separated suffix behind. The inspection view
    # is never returned. Recursive JSON/encoded-text inspection uses this too.
    if "\x00" in value:
        view = value.replace("\x00", "")
        if scrub_string(view, _depth=_depth) != view:
            return "<redacted>"

    if _ENCODED_ESCAPE.search(value):
        if _depth >= 4:
            raise ValueError("encoded content exceeds scrubber nesting limit")
        decoded = unquote(value)
        decoded = _UNICODE_ESCAPE.sub(lambda m: chr(int(m.group(1), 16)), decoded)
        if decoded != value and scrub_string(decoded, _depth=_depth + 1) != decoded:
            # Preserve benign encoded strings byte-for-byte; a changed decoded
            # view proves this entire encoded value contains a credential.
            return "<redacted>"

    # Parse embedded serialized objects so key context survives JSON escaping.
    if value.lstrip().startswith(("{", "[")):
        try:
            decoded = json.loads(value)
        except (ValueError, TypeError):
            pass
        else:
            clean = default_scrub(decoded)
            if clean != decoded:
                return json.dumps(clean, ensure_ascii=False)
            return value  # Every semantic leaf was inspected; retain formatting.
    scrubbed = _EMBEDDED_URL.sub(lambda m: _scrub_url(m.group(0)), value)
    scrubbed = _AUTH_VALUE.sub(lambda m: m.group(1) + "<redacted>", scrubbed)
    scrubbed, _ = redact(scrubbed)
    scrubbed = _KEYED_VALUE.sub(_keyed, scrubbed)
    # Keep existing SDK vendor-prefix coverage, including short synthetic/test
    # credentials. Never use a global entropy sweep: UUIDs and model vocabulary
    # are content, not evidence of a secret.
    return _TOKEN_PREFIXED.sub("<redacted>", scrubbed)


def default_scrub(value: Any, *, key: str = "") -> Any:
    """Scrub credential keys and contents recursively, including opaque reprs."""
    # Typed flags are not credentials, even under names such as
    # `synthetic_credentials_absent`. Strings and numbers still use key context.
    if value is None or isinstance(value, bool):
        return value
    if is_sensitive_key(key.replace("\x00", "")):
        return value if isinstance(value, str) and _indirect_value(value) else "<redacted>"
    if isinstance(value, (bool, int, float)):
        return value
    if isinstance(value, str):
        return scrub_string(value)
    if isinstance(value, dict):
        result = {}
        reserved = {str(item_key) for item_key in value}
        for item_key, item in value.items():
            original = str(item_key)
            clean_key = scrub_string(original)
            candidate = clean_key
            suffix = 1
            while candidate in result or (clean_key != original and candidate in reserved):
                candidate = f"{clean_key}:{suffix}"
                suffix += 1
            result[candidate] = default_scrub(item, key=original)
        return result
    if isinstance(value, (list, tuple, set)):
        return [default_scrub(item, key=key) for item in value]
    try:
        json.dumps(value)
    except (TypeError, ValueError):
        return scrub_string(repr(value))
    return value


# ---------------------------------------------------------------------------
# Free text (exception messages)
# ---------------------------------------------------------------------------
# Diagnostic prose additionally removes home paths; ordinary SDK values keep
# paths, UUIDs and content hashes because they are needed to reproduce runs.

#: Home-anchored absolute paths. The username is the leak, and so is the project
#: directory name -- an unreleased codename is exactly the kind of thing that
#: shows up in a traceback and must not show up in a report.
_HOME_PATH = re.compile(
    r"(?:/(?:Users|home)/[^/\s'\"]+|[A-Za-z]:\\Users\\[^\\\s'\"]+)(?:[/\\][^\s'\"]*)?"
)
#: Vendor-prefixed credentials, matched by their published shapes.
_TOKEN_PREFIXED = re.compile(
    r"\b(?:sk|pk|rk)-[A-Za-z0-9_-]{8,}"
    r"|\bgh[pousr]_[A-Za-z0-9]{16,}"
    r"|\b(?:ros|probe)_(?:pat|ing|svc)_[A-Za-z0-9]{6,}"
    r"|\bxox[abposr]-[A-Za-z0-9-]{10,}"
    r"|\bAKIA[0-9A-Z]{16}\b"
)
#: `KEY=VALUE`, `KEY: VALUE`, `'KEY': 'VALUE'` where KEY reads as a secret.
_ENCODED_ESCAPE = re.compile(r"%[0-9a-fA-F]{2}|\\u[0-9a-fA-F]{4}")
_UNICODE_ESCAPE = re.compile(r"\\u([0-9a-fA-F]{4})")
_AUTH_VALUE = re.compile(
    r"(?i)(\bauthorization[\"']?\s*[:=]\s*[\"']?(?:Bearer|Basic)\s+)"
    r"([^\s\"'<>;,]+)"
)
_ENV_NAME = r"(?:'[A-Za-z_][A-Za-z0-9_]*'|\"[A-Za-z_][A-Za-z0-9_]*\")"
_ENV_LOOKUP = re.compile(
    r"os\.(?:environ[ \t]*\[[ \t]*" + _ENV_NAME + r"[ \t]*\]"
    r"|getenv[ \t]*\([ \t]*" + _ENV_NAME + r"[ \t]*\))"
)
_KEYED_VALUE = re.compile(
    r"(?<![A-Za-z0-9_.-])(?P<q>['\"]?)(?P<key>[A-Za-z_][A-Za-z0-9_.-]*)(?P=q)\s*[:=]\s*"
    # Keep an environment expression's whole RHS together. Only a complete
    # lookup is indirect; concatenation/default literals remain credential data.
    r"(?P<value>os\.(?:environ|getenv)\b[^\r\n;]*|\$\{[A-Za-z_][A-Za-z0-9_]*\}|\"(?:\\.|[^\"\\])*(?:\"|$)|'(?:\\.|[^'\\])*(?:'|$)|(?:\\.|[^\s,&;)}\]\"'\\])+)"
)


def _indirect_value(value: str, *, allow_lookup: bool = True) -> bool:
    if allow_lookup and _ENV_LOOKUP.fullmatch(value.strip()):
        from ._credential_secrets import redact

        # An environment reference is not a waiver for a recognizable credential
        # embedded in its variable name.
        return not _TOKEN_PREFIXED.search(value) and not redact(value)[1]
    return value == "" or bool(re.fullmatch(
        r"\$\{[A-Za-z_][A-Za-z0-9_]*\}|\$[A-Za-z_][A-Za-z0-9_]*|<redacted(?::[a-z0-9-]+)?>",
        value,
    ))


def _keyed(match: re.Match[str]) -> str:
    if not is_sensitive_key(match.group("key")):
        # A generic prefix such as `https:` must not consume a later
        # `?token=...` in malformed URLs or embedded assignments.
        prefix = match.group(0)[:match.start("value") - match.start()]
        return prefix + scrub_string(match.group("value"))
    value = match.group("value")
    quoted = value[:1] in ("'", '"')
    if len(value) >= 2 and value[0] in ("'", '"') and value[-1] == value[0]:
        value = value[1:-1]
    if _indirect_value(value, allow_lookup=not quoted):
        return match.group(0)
    return f"{match.group('q')}{match.group('key')}{match.group('q')}=<redacted>"


def scrub_text(value: str, *, max_chars: int | None = None) -> str:
    """Scrub diagnostic prose, including home paths, then bound its size."""
    if not isinstance(value, str):
        value = str(value)
    scrubbed = scrub_string(value)
    scrubbed = _HOME_PATH.sub("<path>", scrubbed)
    if max_chars is not None and len(scrubbed) > max_chars:
        scrubbed = scrubbed[:max_chars] + f"...<+{len(scrubbed) - max_chars} chars>"
    return scrubbed
